version: '3'
services:
    engine:
        image: "polyswarm/tutorial"
        depends_on:
           - polyswarmd
        environment:
            - POLYSWARM_HOST=polyswarmd
        volumes:
            - "contract:/flag" 
volumes:
    contract:
